volumes:
  postgresql_data:
    driver: local
  keycloak:
    driver: local
services:
  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_DATABASE=keycloak
    volumes:
      - postgresql_data:/bitnami/postgresql
  keycloak:
    image: bitnami/keycloak:latest
    depends_on:
      - postgresql
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=temp
      - KEYCLOAK_ADMIN_PASSWORD=temp
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=keycloak
      - KEYCLOAK_DATABASE_NAME=keycloak
    restart: always
    volumes:
      - keycloak:/bitnami/keycloak
