/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CardsImport } from './routes/cards'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ProductsProductIdImport } from './routes/products.$productId'
import { Route as CheckoutResultImport } from './routes/checkout/result'
import { Route as AuthLoginSuccessImport } from './routes/auth/login-success'

// Create/Update Routes

const CardsRoute = CardsImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsProductIdRoute = ProductsProductIdImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutResultRoute = CheckoutResultImport.update({
  id: '/checkout/result',
  path: '/checkout/result',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginSuccessRoute = AuthLoginSuccessImport.update({
  id: '/auth/login-success',
  path: '/auth/login-success',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsImport
      parentRoute: typeof rootRoute
    }
    '/auth/login-success': {
      id: '/auth/login-success'
      path: '/auth/login-success'
      fullPath: '/auth/login-success'
      preLoaderRoute: typeof AuthLoginSuccessImport
      parentRoute: typeof rootRoute
    }
    '/checkout/result': {
      id: '/checkout/result'
      path: '/checkout/result'
      fullPath: '/checkout/result'
      preLoaderRoute: typeof CheckoutResultImport
      parentRoute: typeof rootRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cards': typeof CardsRoute
  '/auth/login-success': typeof AuthLoginSuccessRoute
  '/checkout/result': typeof CheckoutResultRoute
  '/products/$productId': typeof ProductsProductIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cards': typeof CardsRoute
  '/auth/login-success': typeof AuthLoginSuccessRoute
  '/checkout/result': typeof CheckoutResultRoute
  '/products/$productId': typeof ProductsProductIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cards': typeof CardsRoute
  '/auth/login-success': typeof AuthLoginSuccessRoute
  '/checkout/result': typeof CheckoutResultRoute
  '/products/$productId': typeof ProductsProductIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cards'
    | '/auth/login-success'
    | '/checkout/result'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cards'
    | '/auth/login-success'
    | '/checkout/result'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cards'
    | '/auth/login-success'
    | '/checkout/result'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CardsRoute: typeof CardsRoute
  AuthLoginSuccessRoute: typeof AuthLoginSuccessRoute
  CheckoutResultRoute: typeof CheckoutResultRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CardsRoute: CardsRoute,
  AuthLoginSuccessRoute: AuthLoginSuccessRoute,
  CheckoutResultRoute: CheckoutResultRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/cards",
        "/auth/login-success",
        "/checkout/result",
        "/products/$productId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/cards": {
      "filePath": "cards.tsx"
    },
    "/auth/login-success": {
      "filePath": "auth/login-success.tsx"
    },
    "/checkout/result": {
      "filePath": "checkout/result.tsx"
    },
    "/products/$productId": {
      "filePath": "products.$productId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
